project:
  type: book

book:
  title: "Foundations of Image Systems Engineering"
  author: "Brian A. Wandell and Friends"
  date: "10/20/2024"
  chapters:
    - index.qmd
    - chapters/lightfields.qmd
    - chapters/optics.qmd
    - chapters/sensors.qmd
    - chapters/summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-cap-location: margin
  pdf:
    documentclass: scrreprt
    fig-cap-location: margin


crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section
  
fig-cap-location: bottom
