project:
  type: book
  output-dir: _book 
  resources:
    - chapters/resources/**
    - code

book:
  title: "Foundations of Image Systems Engineering"
  subtitle: "A Guide to Image Formation, Sensors, and Perception"
  version: "v0.1-fall-2025"
  description: "An integrated overview of image systems, from physical scene formation through sensors, optics, and human vision."
  language: en
  output-file: foundations-image-systems
  author:
    - name: Brian A. Wandell
      orcid: 0000-0002-2974-1836
  date: last-modified
  chapters:
    - index.qmd
    - part: "Scenes"
      chapters:
        - chapters/lightfields-01-intro.qmd
        - chapters/lightfields-02-measurement.qmd
        - chapters/lightfields-03-properties.qmd
        - chapters/lightfields-04-properties-spectral.qmd
        - chapters/lightfields-05-properties-spatial.qmd
    - part: "Optics"
      chapters:
        - chapters/optics-01-geometric.qmd
        - chapters/optics-02-lenses.qmd
        - chapters/optics-03-thinlens.qmd
        - chapters/optics-04-morelenses.qmd
        - chapters/optics-05-linear-space.qmd
        - chapters/optics-06-linear-transform.qmd
        - chapters/optics-07-wavefront.qmd
    - part: "Sensors"
      chapters:
        - chapters/sensors-01-photoelectric.qmd
        - chapters/sensors-02-pixels.qmd
        - chapters/sensors-03-parameters.qmd
        - chapters/sensors-04-components.qmd
        - chapters/sensors-05-control.qmd
        - chapters/sensors-06-characterization.qmd
        - chapters/sensors-07-innovations.qmd
    - part: "Human"
      chapters:
        - chapters/part-human.qmd
        - chapters/human-01-seeing.qmd
        - chapters/human-02-optics.qmd
        - chapters/human-03-color.qmd
        - chapters/human-04-spacetime.qmd
    - part: "Displays"
      chapters:
        - chapters/displays-01.qmd
    - part: "Image processing"
      chapters:
        - chapters/imgprocessing-01.qmd
    - part: "Appendix"
      chapters:
        - chapters/appendix-01-linearsystems.qmd
        - chapters/appendix-02-spaceinvariance.qmd
        - chapters/appendix-03-isetcam.qmd
    - chapters/references.qmd

bibliography: paperpile.bib

website:
  title: "Foundations of Image Systems Engineering"
  reader-mode: true
  site-url: https://wandell.github.io/FISE-2025/
  repo-url: https://github.com/wandell/FISE-git
  repo-actions: [edit, issue]

# These are the defaults
execute:
  freeze: auto
  echo: true
  warning: false
  error: false
  message: false
  cache: true
  cache-path: _cache
  cache-scope: global
  progress: true

format:
  html:
    csl:  styles/springer-basic-author-date.csl
    toc: true
    sidebar:
      tools:
        - icon: github
          href: https://github.com/wandell/FISE-git
        - text: "Draft: Fall 2025"
    number-sections: true
    theme: cosmo   # flatly, yeti, sandstone, minty, cerulean, default
    fig-cap-location: bottom
    mathjax: "local"
    math:
      number-equations: true
    css: 
      - styles/hover.css
      - styles/callouts.css 
#  pdf:
#    csl:  styles/springer-basic-author-date.csl
#    documentclass: book
#    number-sections: true
#    keep-tex: true
#    toc: true
#    fig-caption: true
#    fig-cap-location: bottom
#    math:
#      number-equations: true

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section

  

