project:
  type: book
  pre-render: 
    - "quarto render code/*.md --to html"
  render: 
     - "code/*.md"

book:
  title: "Foundations of Image Systems Engineering"
  author:
    - name: Brian A. Wandell
      orcid: 0000-0002-2974-1836
  date: last-modified
  chapters:
  - index.qmd
  - part: "Scenes"
    chapters:
    - chapters/lightfields-1.qmd
    - chapters/lightfields-2.qmd
    - chapters/lightfields-3.qmd
    - chapters/lightfields-4.qmd
  - part: "Optics"
    chapters:
    - chapters/optics-1.qmd
  - part: "Sensors"
    chapters:
    - chapters/sensors-1.qmd
  - part: "Human"
    chapters:
    - chapters/human-1.qmd
  - part: "Image processing"
    chapters:
    - chapters/imgprocessing-1.qmd
  - part: "Displays"
    chapters:
    - chapters/displays-1.qmd
  - part: "ISETCam"
    chapters:
    - chapters/isetcam-1.qmd
  - chapters/references.qmd
resources:
   - resources/lightfields-wavebands.html
   - resources/optics-diffraction.html
   - resources/optics-abcd.html
   - code/*.md


# footnotes in margin.  Testing.
# reference-location: margin 

bibliography: paperpile.bib

jupyter: matlab

format:
  html:
    header-includes: \usepackage{siunitx}
    toc: true
    number-sections: true
    theme: cosmo
    fig-cap-location: margin
    render-on-save: true
  
# pdf:
#    documentclass: scrreprt
#    fig-cap-location: bottom

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section
  
