project:
  type: book

book:
  title: "Foundations of Image Systems Engineering"
  author: "Brian A. Wandell and Friends"
  date: "10/20/2024"
  chapters:
    - index.qmd
    - lightfields.qmd
    - optics.qmd
    - sensors.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section
  
fig-cap-location: bottom
