project:
 type: book
 output-dir: _book 
 resources:
 - resources/
 - code/

book:
 title: "Foundations of Image Systems Engineering"
 author:
   - name: Brian A. Wandell
     orcid: 0000-0002-2974-1836
 date: last-modified
 chapters:
   - index.qmd
   - part: "Scenes"
     chapters:
       - chapters/lightfields-intro.qmd
       - chapters/lightfields-diffraction.qmd
       - chapters/lightfields-measurement.qmd
       - chapters/lightfields-properties.qmd
       - chapters/lightfields-properties-spectral.qmd
       - chapters/lightfields-properties-spatial.qmd
   - part: "Optics"
     chapters:
       - chapters/optics-principles.qmd
       - chapters/optics-geometry.qmd
       - chapters/optics-linear.qmd
       - chapters/optics-wavefront.qmd
   - part: "Sensors"
     chapters:
       - chapters/sensors-1.qmd
       - chapters/sensors-2.qmd
       - chapters/sensors-3.qmd
       - chapters/sensors-4.qmd
       - chapters/sensors-5.qmd
   - part: "Human"
     chapters:
       - chapters/human-1.qmd
   - part: "Image processing"
     chapters:
       - chapters/imgprocessing-1.qmd
   - part: "Displays"
     chapters:
       - chapters/displays-1.qmd
   - part: "Appendix"
     chapters:
       - chapters/appendix-isetcam-1.qmd
       - chapters/appendix-linearmodels.qmd
   - chapters/references.qmd

bibliography: paperpile.bib

jupyter: matlab

format:
 html:
   toc: true
   number-sections: true
   theme: cosmo
   fig-cap-location: margin
   render-on-save: true

crossref:
 fig-prefix: Figure
 tbl-prefix: Table
 sec-prefix: Section