project:
  type: book

book:
  title: "Foundations of Image Systems Engineering"
  author: "Brian A. Wandell and Friends"
  date: "10/20/2024"
  chapters:
    - index.qmd
    - chapters/lightfields.qmd
    - chapters/optics.qmd
    - chapters/sensors.qmd
    - chapters/human.qmd
    - chapters/displays.qmd
    - chapters/summary.qmd
    - references.qmd
  appendices:
    - supplemental/lightfields-wavebands.qmd
    - supplemental/optics-abcd.qmd
    - supplemental/optics-diffraction.qmd

bibliography: 
  - references.bib
  - fise.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    fig-cap-location: margin
  
# pdf:
#    documentclass: scrreprt
#    fig-cap-location: bottom

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section
  
