project:
  type: book

book:
  title: "Foundations of Image Systems Engineering"
  author:
    - name: Brian A. Wandell
      orcid: 0000-0002-2974-1836
  date: last-modified
  chapters:
    - index.qmd
    - chapters/lightfields.qmd
    - chapters/optics.qmd
    - chapters/sensors.qmd
    - chapters/human.qmd
    - chapters/displays.qmd
    - chapters/summary.qmd
    - references.qmd

resources:
   - resources/lightfields-wavebands.html
   - resources/optics-diffraction.html
   - resources/optics-abcd.html

# footnotes in margin.  Testing.
# reference-location: margin 

bibliography: paperpile.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    fig-cap-location: margin
  
# pdf:
#    documentclass: scrreprt
#    fig-cap-location: bottom

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  sec-prefix: Section
  
