# Sensors

## Historical sensor types

Film was the first major commercial technology for capturing and storing image irradiance, and it relied heavily on chemistry. Light-sensitive molecules were coated onto flexible rolls of plastic, which were then loaded into a camera.

![Film was the dominant image sensor and recording material for a hundred years. The chemistry of film for both encoding and developing into images was the core scientific discipline. Film could not be reused, producing a steady commercial profit for large companies, such as Kodak, Fuji, Polaroid and Agfa.](images/sensors/film.png){#fig-film width="60%"} 

Inside the camera, the film was mechanically advanced so that a small, flat section would be positioned at the focal plane of the lens. This section of the film was exposed to the focused light (electromagnetic radiation) that passed through the camera’s optics. The light altered the molecular structure of the film, with more molecules being changed in areas of higher light intensity and fewer in areas of lower intensity. These molecular changes represented the local brightness of the captured image. Using sophisticated chemical processes, different light-sensitive molecules could be designed to respond to specific wavelengths of light, selectively ignoring others. After exposure, additional chemical treatments developed the film and transformed it into a printed image. This process was resource-intensive, requiring a variety of chemical consumables, as the film could not be reused, and specialized labs were needed for both development and printing.

A completely different approach to capturing radiance emerged with the discovery by Willard S. Boyle and George E. Smith at Bell Labs that semiconductor technology could also be used to record irradiance. Light striking silicon releases electrons (photoelectric effect), and the spatial pattern of these electrons could be stored and measured. This breakthrough was first implemented in 1970 by Michael Tompsett, who developed the image sensor known as the charge-coupled device (CCD).

The semiconductor based sensor revolutionized imaging, moving it from a field based on chemistry to electrical engineering. This method required no consumables (chemicals). Importantly, the digital readout from these electrical devices could be immediately integrated with computers. Images could be stored, shared, edited and analyzed directly from the camera output. The step from the CCD sensor to the CMOS sensor was another major advance that unleashed a massive adoption of electronic image sensors around the world.

This chapter is about the properties of the CMOS image sensors used to measure radiance. In later sections we will also describe how semiconductor sensor can be used to estimate depth, as well. Because there are significant differences in these technologies and the information they acquire, we treat them in separate sections.