# Fisher and the scientific method
---
title: "Project Muse - R.S. Fisher and statistics"
date: last-modified
---

I spent a lot of time thinking about this.  But I don't have a place for it yet.

# Project Muse {.unnumbered}

::: {.callout-note collapse="true" title="Discovery and context"}
## Intellectual atmosphere

"The History of Science has suffered greatly from the use by teachers of second-hand material, and the consequent obliteration of the circumstances and the intellectual atmosphere in which the great discoveries of the past were made. A first-hand study is always instructive, and often . . . full of surprises." (Ronald A. Fisher, in [@fisher-mendel-1955])

The great and influential statistician, Ronald Fisher, wrote this comment in 1936, though it was published much later by his estate. He believed that the experiments reported by Mendel included some improperly collected or analyzed data. He urges us to make the distinction between secondary reporting of findings and fully appreciating the context and intellectual mieliu of the original work. His commentary goes back to the history in a thoughtful way.

In my view, this is too much to ask of all teachers at all times. But it is not too much to ask of some of us. I should add that having now read several of Fisher's original papers, and I am aware of his context including some views that I find entirely wrong (Project Muse). I find him and the world he represents a bit terrifying. But the importance of his contributions cannot be ignored.
-->