# Human visual system

The purpose of many image systems is to record information about the light field and then render that information in print or on a display for viewing by a human. The components of these systems, typically for consumer photography, deliver information to the human visual system. For this reason, they must be designed with the key properties of the human visual system in mind.

This chapter describes those key human visual system properties, formulating the measurements and principles for those interested in engineering applications. I describe the measurements of human performance and the human performance metrics that have been adopted by international standards bodies or that are in widespread use in industry.

For those interested in the biological basis of these performance measurements, I provide brief call-outs within the text with some background. For a deeper dive into the biology, please consult the book Foundations of Vision [@wandellFoundationsVision1995]; that book is devoted to vision science and emphasizes neuroscience more than engineering.

The software examples included in this chapter mainly rely on the combination of ISETBio and ISETCam.

<!--# The chapters with David have a lot of the material.  -->

## Initial encoding

The human eye description.

Measurements of human optics from ISETBio.

## Physiological optics

But some description of the retina and photoreceptors. What about the color matching experiment? Maybe James Clerk Maxwell goes here?

## Color

Color spaces Color ellipses

## Pattern

sMTF

### Time and motion

tMTF

## Color image quality metrics

CIELAB and so forth

## CIELAB

## S-CIELAB

## Mark Fairchild stuff

## Other color metrics???

## Pattern image quality metrics

SSIM. Simpler ones. Pyramid from Beau? But earlier single channel, multiple channel.

### SSIM and MS-SSIM

### Sharpness metrics

I forget the guy

### Computer vision metrics?

Note that they exist but they should go elsewhere.