---
date: last-modified
---

# Human visual metrics {#sec-human-metrics}
{{< include "includes/WIP-callout.qmd" >}}

<!--
# Thinking about Bob Hunt.  https://www.perplexity.ai/search/robert-hunt-from-kodak-researc-pIEYaPICQzWNhpK4mWIcCQ -->
-->

# Human visual metrics topics {#sec-human-metrics-overview}

Summary of what is to come.

## Color representations 

Color representations: XYZ, luminance, chromaticity, cones

## Color metrics
Color discrimination: ellipses

CIELAB

S-CIELAB

Mark Fairchild contributions. Others?

## Pattern metrics

spatial MTF - Look through modern measurements of the spatial MTF.

ISO 12233

## Temporal metrics

temporal MTF

## Multi-parameter metrics

Watson Pyramid observation?

## Image quality metrics {#sec-human-imagequality}

SSIM. Simpler ones. Pyramid from Beau? But earlier single channel, multiple channel.

SSIM and MS-SSIM

Sharpness metrics

I forget the guy with a B, I think

temporal MTF. Flicker.

Mantiuk

The surprising metric

## Computer vision metrics for color?

They should be described elsewhere.

A lot of these might have been used in those directional cosine errors in Zheng's dissertation
