---
date: last-modified
---

# Human optics {#sec-human-optics}
{{< include "includes/WIP-callout.qmd" >}}

## Human optics overview {#sec-human-optics-overview}
I will develop this around human adaptive optics.  Either here or in FOV.

::: {.callout-note title="Shack-Hartmann wavefront sensor"}

### Shack–Hartmann wavefront sensor {#sec-wavefront-sensor}
Johannes Franz Hartmann was a German astronomer working on the problem of detecting optical defects in telescope objectives. Reasoning  from the ray theory of light, he measured the optical light field from a simple stimulus:  an on-axis point at the focal length of the lens. In principle, the rays emerging from an ideal lens would all be parallel to the main axis.  To look for deviations, he created a screen comprising an array of pinholes.  If the rays were parallel, the light through the pinhole would be nicely centered behind the pinhole.  If the rays were not quite parallel, the image behind the pinhole would be displaced by some distance and amount from the center.  The deviations could be considered defects in the lens that could be corrected.

As I observed above, the image behind each pinhole measures the intensity of the rays incident at different angles. But in practice, a small pinhole produces a blurry spot due to diffraction. Thus Hartmann did not try to extract an image but he just estimated the central position of the blurry spot. Also, because the pinholes only let through a small amount of light, the technique was not very sensitive.

Because there is an array of these pinholes, the accumulation of pinhole images measures the rays at multiple angles at multiple positions. In principle, by performing this measurement for different wavelengths and polarizations, we sample the optical light field (@eq-lightfield-optical).

<!--
The Raskar version in which you put spots behind the lenslet array and adjust the spots to make the array uniform is kind of funny.  It is intended to measure the optical aberrations of the eye
https://en.wikipedia.org/wiki/Shack%E2%80%93Hartmann_wavefront_sensor
-->

[Arizona History of the Shack work.](https://www.optics.arizona.edu/sites/default/files/2022-07/Historical-Development-Shack-Hartman-Wavefront-Sensor.pdf?utm_source=chatgpt.com)

### Adaptive optics  {#sec-adaptive-optics}

### Ground-based telescopes {#sec-telescopes}

These same technologies can be used to look inward, within the eye, rather than outward toward the stars. Realizing this was a very important insight that continues to lead to important insights about the peripheral human visual system (@sec-human). 

:::
