---
date: last-modified
---

# Image processing principles {#sec-imgprocessing-principles}
{{< include "includes/WIP-callout.qmd" >}}

## Image processing principles overview {#sec-imgprocessing-principles-overview}

The general field of digital image processing is enormous. It was large when I was a graduate student, and with time it has grown even more massive. It seems that whenever a new computational concept emerges, it finds application in imaging and expands the field.  The most recent expansion is the use of deep neural network tools to create and edit images and videos. These are fascinating and 

In 

To this point, we have considered the environmental light field [@sec-light-overview], how it is measured by the optics [@sec-geometric-optics], and how it is then converted into electrons at each pixel [@sec-pixels-overview]. We have also considered how the visual system would capture the same light field.  

The first part of this chapter on image processing describes the steps that converts the data measured by the sensor into a signal that can be viewed by a person.

It seems as if we should have display go first so we can do it.  Or we might just assume that people know displays are typically RGB and hope for the best?  

Also, the human section on color might include some minimal display description that we could use here as the basic display model, with more advanced displays to come later, in the chapter @sec-display-principles-overview.

## Lens shading

## Acquisition policies

## Demosaicking

Space-color correlations?

## Color processing

### Sensor correction

### Illuminant correction







