## Environmental light field properties {#sec-lightfield-properties}

Many image systems are designed to enable engineers to recover physical properties of the scene from the light field. We might want to recover the size of an object, its distance, its wavelength reflectance. We may might want to estimate the intensity and spectral characteristics of the lighting. Or we might want to find particular types of objects or textures. Such systems are at the foundations of applications such as part inspection, autonomous driving, and medical imaging. Some ability to estimate the physical characteristics of the scene is also important for aspects of consumer photography, such as illuminant correct.

In this section we describe some of the information that has been accumulated about central tendencies of light fields we typically encounter in nature. The way we characterize these statistical regularities is probably more important than the regularities themselves. I say this because in each environment we encounter - underwater imaging, aerospace, medical, nature photography - the regularities might differ. But the idea that there are regularities and that we should incorporate this information in our methods is quite general.

### Spectral regularities

A particularly surprising, and yet profound, regularity of the environmental light field is the spectral power distribution of skylight. The sun provides a relatively stable source of electromagnetic radiation in the visible range, and this illuminates the earth's atmosphere. The light arriving at the surface passes through different amounts of atmosphere as the earth rotates. Also, the characteristics of the atmosphere, in particular its water and particle concentration, vary considerably as the weather changes.

The importance of daylight for applications from consumer photography to remote sensing made it an early object of study.

The earliest measurements of wavelength revealed the Fraunhofer lines. I should mention that. What are they and ...

Daylight spectral model. Judd Macadam and Wyszecki.

Surface reflectance linear models.

<!--# Moonlight regularities.  Used for space travel.https://chatgpt.com/share/67410dd0-ff54-8002-9b73-65294a849fe6  “The Potential of Moonlight Remote Sensing: A Systematic Assessment” explores the potential of using moonlight in remote sensing for nighttime Earth observation. The study uses data from VIIRS, the ISS, and UAV systems to evaluate moonlight’s capabilities.“Simulation Study of the Lunar Spectral Irradiances and the Earth-Based Moon Observation Geometry” focuses on modeling the spectral irradiance of moonlight using the Hapke model and its applications in satellite radiometric calibration.-->

### Spatial regularities

Spatial frequency fall off

Dead leaves model. FInd the Winawer Matlab script.