# Light fields {#sec-lightfields}
Why do organisms sense and interpret their surroundings? From a biological perspective, sensory perception is fundamental for guiding movement, enabling animals to locate resources, avoid threats, and navigate their environments. Ambient electromagnetic radiation provides a rich and reliable stream of information, which mobile organisms—whether a hawk, a rabbit, or a human—analyze to make decisions and interact with their surroundings. For immobile life forms, such as trees and plants, this radiation serves primarily as a source of energy, rather than information.

In robotics, visual sensing serves a similar fundamental purpose: to enable movement and interaction within complex environments. By equipping robots and autonomous vehicles with imaging systems, we allow their computer programs to interpret visual data so they can identify, reach, and navigate through their surroundings, closely paralleling the biological role of sensory systems in guiding adaptive, goal-oriented actions.

Not all electromagnetic radiation is equally informative. High energy radiation (e.g., X-ray and Gamma ray bands) passes through most objects undisturbed. Low frequency radiation provides limited spatial resolution. The human eye detects electromagnetic radiation in the wavelength range from about 380 nm to 770 nm. We call this waveband "light", which is defined as "electromagnetic radiation that can be detected by the human eye." Electromagnetic radiation in this wavelength range is strongly absorbed and reflected by objects of interest, making it a very useful band for informing us about the environment.

Some image systems are designed to measure light because we want them to reproduce the signals that we might see. Others measure light because the signal is useful for their own function. And finally, some image systems measure electromagnetic radiation at wavelengths we do not see, exploring domains within the environment that are beyond our senses[^lightfields-1-1].

[^lightfields-1-1]: See [more about wavebands here.](../supplemental/lightfields-wavebands.html){target="_blank"}.

::: {.callout-note collapse="true" title="Who needs a brain?"}
### Movement requires a brain {.unnumbered}

The deep connection between mobility, sensing and the brain is illustrated by the remarkable life path of the [sea squirt](https://movementum.co.uk/journal/sea-squirts). It begins life as tadpole-like larvae, equipped with a brain and a tail for swimming. Once the tadpole finds a suitable spot to settle, it attaches to a hard surface like a rock or coral and becomes immobile.

As soon as the sea squirt fixes itself to the rock, with no more navigation or swimming, its brain is no longer needed. In a truly bizarre twist, the sea squirt digest its own brain. This adaptation reallocates energy resources from the now unnecessary brain to more vital functions.

Here are some [nice images of sea squirts!](https://goodheartextremescience.wordpress.com/2010/01/27/meet-the-creature-that-eats-its-own-brain/)\
<!-- Irv Weissmann has lots of neurodegeneration papers on this -->
:::

{{< include lightfields-1.qmd >}}
{{< include lightfields-2.qmd >}}
{{< include lightfields-3.qmd >}}
{{< include lightfields-4.qmd >}}
