# Harmonic characterization {#sec-optics-characterization}

## Harmonic characterization overview
There are many reasons why people would like to describe the quality of an optical system.  Commercial vendors that sell parts may need to specify the quality and the tolerance of the quality measure.  We may want to optimize the properties of a design, using the image quality measure as a metric for the optimization.  We may wish to simulate the system and learn which signals are preserved by the optics and which are lost to image quality.

The point spread function is a very intuitive way to understand the performance of the optical system. But, it is not a great general tool to quantify image quality. We can quantify the shape of the point spread function for the simplest cases (Airy pattern). And there are some simple point spread shapes with a small number of parameters that are useful for simulation (@sec-pointspread-common). But these instances are not sufficient to approximate many real lenses, multielement lenses, or measurements of the human eye.

Harmonic functions are a tool to help with system characterization. Their value arises from this simple and important fact:  When the input to an optical system is a harmonic function at spatial frequency $f$ and unit contrast, in each local region the image will also be a harmonic function at the same frequency.  The relative phase and amplitude of the output will differ from the input, but we only need to measure these two parameters.  

This chapter explains the general principle and then provides several ways in which harmonics are used to characterize optical systems as well as the human visual system.

## System eigenfunctions

An **eigenfunction** of a system is an input that whose output is the same as the input, up to a scale factor.  Harmonics are almost eigenfunctions. This is a very useful fact to know about a system because it means when we use an eigenfunction as input, we know almost everything about the output.  In symbols, if $\mathbf{L}$ is a matrix that represents a discrete linear system, the column vector $\mathbf{e}_i$ is an eigenfunction if

$$
\alpha_i \mathbf{e}_i = \mathbf{L} \mathbf{e}_i 
$$ {#eq-eigenfunction-definition}

The scalar values, $\alpha_i$ are the **eigenvalues** of the linear transformation. 

An important and somewhat remarkable fact about the collection of eigenfunctions of a linear system is this:  they are an orthogonal basis of the possible inputs.  Thus, any input, say a stimulus column vector $\mathbf{s}$, can be described uniquely as the weighted sum of the eigenfunctions,

$$
\mathbf{s} = \sum_i s_i \mathbf{e}_i .
$$

This means if we represent the stimulus with respect to the eigenfunctions, and we know the eigenvalues, we can predict the response to the stimulus.

$$

$$



If the input is a harmonic of frequency $f$, the output will be a scaled version of that harmonic.  It is not a perfect eigenfunction only because there can also be a phase shift. This input-output simplicity makes the harmonics very useful tools for system characterization.

The mathematics 

## Optical Transfer Function {#sec-optical-transfer-function}


## Modulation Transfer {#sec-modulation-transfer-function}


## Contrast sensitivity {#sec-contrast-sensitivity-function}


