# Optics as a linear system {#sec-optics-linear}
Geometric optics is helpful for understanding and characterizing many optical system properties. The ideas in geometric optics are closely tied to the physical properties of the lenses which makes geometric optics a particularly valuable tool in lens design.

Another way to consider an optical system is to think of how the radiation incident at the entrance aperture is transformed into radiation incident at the sensor surface.  This point of view treats the optics as transforming one spctral image (the irradiance from the incident light field) into a second spectral image (the irradiance at the sensor surface).  This characterization of the optics is thinking of the system in terms of signal processing, a valuable approach for system simulation.  

This treatment is particularly important for optics because so many important optical systems are linear.  Specifically, they satisfy the (testable) experimental property called the **Principle of Superposition**. Linear systems are found in many science and engineering disciplines, and we will see the idea repeatedly and in many different contexts in the rest of this book.  

## Principle of superposition
When characterizing a system, the scientist or engineer's first hope is that its input-output relationship is approximately linear. We say a system, $L$, is linear if it satisfies the superposition rule: $$L(x + y) = L(x) + L(y).$$ The variables $x$ and $y$ are two possible inputs to the system, and $x+y$ is their superposition. $L(x)$ is the output of the system.  In the optical system case that we are considering, $x$ might be the spectral image at the entrance aperture of the optics and $L(x)$ might be the spectral image at the exit aperture.

There is a specialization of superposition that is often separated out: ** Homogeneity**, which is $L(\alpha x) = \alpha L(x)$. Homogeneity is a consequence of the superposition rule. Consider that

$$\begin{aligned}
L(x + x) &= L(2x) \nonumber  \\ 
&= L(x) + L(x) \nonumber \\
&= 2L(x). \nonumber
\end{aligned}$$

This is easily generalized for any integer $m$ to show that [^optics-linearity]

$$L(m x) = m  L(x).$$

If you put enough energy into a system it will blow up - so no system satisifies linearity over an infinite range. But many systems are linear over a meaningful input range (sometimes call their *compliance range*).

[^optics-linearity]: Real-valued systems that follow the superposition rule obey the homogeneity rule for any real scalar, not just for integers. It is useful to remember that some systems obey homogeneity but not the superposition. For example, $f(x) = \lvert x \rvert$, and $f(x) = x^2$ both satisfy homogeneity, but not superposition.

## Shift-invariant linear systems

The whole system may not be shift invariant because of geometric distortion.  But there may be various regions of the visual field over which shift invariance is a good approximation (for small shifts).  These are called isoplanatic regions.  One can often have an isoplanatic region near the main optical axis of a system.

How do we express if we translate an image by some amount, $\delta$, and represent this as $T(x,\delta)$, then 

$$L(T(x,\delta)) = T(L(x),\alpha \delta)$$.  

The size of the shift differs on the input and output.

OTFs.  MTFs.


### Point spread functions

### Line spread functions

Relationship between point spread and line spread. psf2lsf easy, but to go back you need to assume something about the circular symmetry.

## Harmonics and shift-invariance
Almost eigenfunctions.  Not quite.
Relationship between OTF and PSF.

### Optical Transfer Function
### Modulation Transfer
### Contrast sensitivity

## Chromatic aberration

This is already in, earlier.  Maybe an example here? Explain transverse and longitudinal chromatic aberration here? 





