# Thin lens {#chapter-optics-thinlens}

The thin lens model is an important conceptual tool in optics. It provides a clear framework for understasnding key concepts like, focal length, magnification, and in general image formation. Moreover, practical systems are often made from components that include - or at least are well approximated by - a collection thin spherical lenses. We can describe these systems by understanding how multiple thin spherical lenses combine to form an optical system.

![A thin lens has a width that is much smaller than the radius of curvature of its surface. (a) This lens is about 10 times smaller than the radius of the circle that matches its surface. Thus might be considered thin. (b) This lens width is approximately equal to the radius of curvature. It would not be a thin lens.](../images/optics/thinlens-definition.png){#fig-thinlens-definition fig-align="center" width="60%"}

Add in the radius of curvature definition of thin lens from the class slides.

Define the F-number and its importance for thin lenses. Why it is the single, key parameter.

Lensmaker’s equation derivation which is from Gauss and I think I teach as Psych 221 slides.

Graph of focal distance to image plane as a function of object distance.  Notice that the object focal plane approaches a constant and stays near that level for a very large distance range.

This is connected to f-number and to radiometry.  Maybe not here? Question of distance trading off with magnification for constant intensity per unit area with distance to the wall.

Magnification and Zoom. Depth of field formula. The sequence from class slides.


