# Sensor systems
Images are captured under a wide variety of conditions, and there is no single set of parameters—such as focus, exposure time, or sensor gain—that guarantees high-quality results in every situation. To address this, sensors are equipped with control systems that automatically adjust acquisition parameters. These systems help prevent pixel saturation, reduce image noise, and set optical properties like focal plane and depth of field. In computer vision applications, such as robotics or autonomous driving, these control systems are essential for obtaining reliable quantitative data. In consumer photography, they assist users in quickly achieving settings that produce visually appealing images.

The sensor control systems are typically implemented by the commercial vendors. The general principles of these control methods can be described, but the specific implementations can be quite complex, with many parameters, and are trade secrets. Moreover, the control systems themselves need to be adjusted in various ways that depend on the details of the optics and sensor in the camera. This section describes the principles of the control systems.  It is my view that there are opportunities to develop better open standards for designing and evaluating these control systems through simulation. 

## Focus
It is important that a camera be capable of setting the lens so that the critical objects are rendered into good focus at the sensor.  There are some cases in which this is relatively straightforward.  (Everything is expected to be far away.)

### Classic autofocus

### Dual pixel autofocus


## Exposure and gain control

### Classic exposure 

### Exposure bracketing

### Burst photography
Google but others.  Multiple capture.

## System innovations {#sec-sensor-innovations}

Maybe this should be an additional chapter

Over time, as technology has scaled, more complex electrical circuitry has been placed on the sensor. Modern image sensors frequently include circuitry that performs local processing to increase the dynamic range of the sensor (well recycling), or to reduce the intrinsic noise (correlated double sampling). Some of this processing is *adaptive*, that is the circuit actions depend on the property of the input image. Consequently, the sensor output can depend upon both the control parameters set by the user and the image content.

### Global shutter {#sec-sensor-globalshutter}
Instead of using a floating diffusion as a memory element, Aptina has utilized a surface-pinned storage node in the pixel to address dark current challenges. Available in its newest global shutter sensor, the MT9M031, the storage node also enables using a true correlated double sampling technique to reduce readout noise to four electrons, resulting in excellent low-light performance. The combination of the effective use of an anti-reflective metal light shield in close proximity to the memory node and careful doping and potential profile design results in a high GSE.

Illustrate rolling shuttter artifact.

Then say something about global shutter technology.

Global Shutter Pixel Technologies and CMOS Image Sensors – A Powerful Combination – (Aptina white paper)

Well recycling?
### Lightfield cameras {#sec-sensor-lightfield}
Refocus.  Depth estimation

### Split pixel {#sec-sensor-splitpixel}
Autonomous driving.  HDR.

### Foveon {#sec-sensor-foveon}
Link back to physics.

### Spectral imagers {#sec-sensor-spectral}
Spectricity.  IMEC.


