# Sensor optics {#sec-sensors-components}

## Optical components

There are also other non-electrical components of most image sensors. These are small lens (lenslet) arrays and small color filter arrays that influence which part of the irradiance is capable of producing electrons from each photodiode.

The sensor records the light that exits from the back of the imaging optics. The photodiodes are small and they are located at the bottom of small holes in the sensor. It is necessary to guide the irradiance from the camera lens with an array of microlenses that account for the position of the pixel with respect to the center of the lens. The original role of the microlens array was to compensate for the challenges inherent in this geometry. Overtime, the microlens array has been designed to achieve additional objectives including determining how to focus the image and estimate the scene light field.

To make a color image, the sensor must measure some information about the relative intensity of different wavelengths. To make this measurement small color filters are placed in front of each pixel, so that different pixels are sensitive to different wavelengths. These spectral encoding differences enable the system to reconstruct a color image that is convincing to the human visual system.

### Microlens arrays

Light field possibility.



