#!/usr/bin/env bash
set -e

# Define target directory inside user's home folder
TARGET_DIR="$HOME/isetcam"

echo "Setting up ISETCam..."

# Clone ISETCam if it doesn't already exist
if [ ! -d "$TARGET_DIR" ]; then
    echo "Cloning ISETCam repository into $TARGET_DIR..."
    git clone https://github.com/ISET/isetcam.git "$TARGET_DIR"
else
    echo "ISETCam directory already exists at $TARGET_DIR."
fi

# Ensure MATLAB startup folder exists
STARTUP_DIR="$HOME/matlab"
mkdir -p "$STARTUP_DIR"

export MWI_ENABLE_TOKEN_AUTH=False

# Add ISETCam to MATLAB startup.m
STARTUP_FILE="$STARTUP_DIR/startup.m"
echo "Configuring MATLAB startup.m..."

cat << 'EOF' > "$STARTUP_FILE"
% Automatically generated by .devcontainer/setup.sh
addpath(genpath('~/isetcam'));
disp('===================================================');
disp('  ISETCam successfully loaded onto MATLAB path!    ');
disp('===================================================');
EOF

touch ~/.startmatlabdesktop

echo "Setup complete!"
