%% fise_humanMosaic
%
% Simulated mosaic from ISETBio
%

%{
%% From NC
sigmaGaussian = 0.204;  % From McMahon et al, 2000
coneApertureModifiers = struct(...
    'smoothLocalVariations', true, ...
    'sigma',  sigmaGaussian, ...
    'shape', 'Gaussian');

%%
cM1 = cMosaic(...
    'sourceLatticeSizeDegs', 64, ...
    'eccentricityDegs', [6 0], ...
    'sizeDegs', [8 1], ...
    'whichEye', 'right eye', ...
    'eccVaryingConeBlur', true, ...
    'rodIntrusionAdjustedConeAperture', true, ...
    'coneApertureModifiers', coneApertureModifiers, ...
    'randomSeed', 1234);

[uData,hdl] = cM1.plot('mosaic');
ieFigureResize(hdl);
%}

%% Create a set of square patches, 1 x 1 deg into the periphery

eccDeg = [0 0; 1 0; 3 0; 6 0; 12 0];
for ii=1:size(eccDeg,1)

    cm = cMosaic(...
        'sourceLatticeSizeDegs', 64, ...
        'eccentricityDegs', eccDeg(ii,:), ...
        'sizeDegs', [1 1], ...
        'whichEye', 'right eye', ...
        'eccVaryingConeBlur', true, ...
        'rodIntrusionAdjustedConeAperture', true, ...
        'coneApertureModifiers', coneApertureModifiers, ...
        'randomSeed', 1234);

    [uData,hdl] = cm.plot('mosaic');
    ieFigureResize(hdl);

    fname = sprintf('coneMosaic-%d-deg.svg',eccDeg(ii,1));
    fname = fullfile(fiseRootPath,'chapters','images','human','02-encoding',fname);
    print(gcf,fname,'-dsvg');
    % pause;
end

%% END